### PR TITLE
added unit file for phoebe-network

### PR DESCRIPTION
**Pull request by mslacken**
*Do not approve pr*
`network.service` should  got to the directory `dist`, but I don't know how to do that.

### CODE REVIEW

**Comment by mvarlese** [comment]
> _Do not approve pr_
> `network.service` should got to the directory `dist`, but I don't know how to do that.

No worries, the CI is broken so it won't be merged ;)

**Comment by mslacken** [comment]
Now it can be merged

**Comment by mvarlese** [comment]
Nope, it cannot: CI still failing... you need to clang-format your patch

**Review by mvarlese — CHANGES_REQUESTED** [review]
@mslacken you need to add **systemd** to the file _.github/workflows/ci.yml_ at line 138

**Review by mvarlese — CHANGES_REQUESTED** [review]
You need to bump the version exported in 

https://github.com/SUSE/phoebe/blob/main/.github/workflows/rpmbuild.yml

**Comment by mvarlese** [comment]
Cool. Thanks!

**Pull request merged**
