### PR TITLE
write_log has now a global verbosity level

### PR DESCRIPTION
**Pull request by mslacken**
Not happy with the approach right now, as we the global variable `unsigned int verbosity_level` in every binary and library

### CODE REVIEW

**Comment by mvarlese** [comment]
Please, try to rework this patch using a get()/set() API approach.
I try at all cost not to use **extern** variables in the code...

**Review by mvarlese — CHANGES_REQUESTED** [review]
Rework with get() / set() API approach to avoid usage of **extern**

**Comment by mslacken** [comment]
> Rework with get() / set() API approach to avoid usage of **extern**

calliing a get() in an inlined function does not make that much sense, imho

**Comment by mvarlese** [comment]
> > Rework with get() / set() API approach to avoid usage of **extern**
> 
> calliing a get() in an inlined function does not make that much sense, imho

you can still make the function an inline one (as already done in other parts of the code)...

**Comment by mslacken** [comment]
Moved the variable verbosity_level to the utils.c so that not object file has its own copy.
So inlining is not possible any more.

**Review by mvarlese — CHANGES_REQUESTED** [review]
@mslacken this patch includes several changes, many of which have nothing to do with the actual commit message. For example, it contains also some changes which were already pushed with the separate patch for the service file. Can you please clean this up?

**Comment by mslacken** [comment]
Messed up with a local rebase, so closing ths PR

**Pull request closed without merging**
