### PR TITLE
Remove SETUP.md

### PR DESCRIPTION
**Pull request by shunghsiyu**
SETUP.md contains information about our Lab setup. Unforunately, the setup is only accessible to SUSE employee.

While there is nothing secretive about our lab setup, it does not make much sense for this to live directly inside the repository now that the repository itself is public.

The original content has been moved to https://github.com/SUSE/phoebe/wiki/Lab-Setup instead.

### CODE REVIEW

**Comment by shunghsiyu** [comment]
Latest changes to SETUP.md (in commit 4796d795fcba6db2230c20b8f7cb770a9ca55f2b) has been applied to our wiki page as well

**Comment by mvarlese** [comment]
@shunghsiyu you need to remove **SETUP.md** from the spec file (_dist/rpm/phoebe.spec_)

**Comment by shunghsiyu** [comment]
@mvarlese thanks for the pointer, done!

**Comment by mvarlese** [comment]
Thanks!

**Pull request merged**
