### PR TITLE
set the right plugin path in settings.json on install

### PR DESCRIPTION
**Pull request by mslacken**
Signed-off-by: Christian Goll <cgoll@suse.com>

### CODE REVIEW

**Comment by dcermak** [comment]
Hm, I actually think that it could be worthwhile to make the `plugin_path` configurable, as not every distribution might want to install plugins to `%_libdir` (I think `%_libexecdir` might be a better fit depending on the distro policy).

**Comment by mvarlese** [comment]
@dcermak the plugins path is already configurable...

**Comment by mslacken** [comment]
> Hm, I actually think that it could be worthwhile to make the `plugin_path` configurable, as not every distribution might want to install plugins to `%_libdir` (I think `%_libexecdir` might be a better fit depending on the distro policy).

I just took the path which was already there, so this would require changes in other places. This pr, just makes the phoebe useable without the need of an extra edit of the configuration files.

**Comment by dcermak** [comment]
> @dcermak the plugins path is already configurable...

Not from meson though.

**Comment by dcermak** [comment]
> > Hm, I actually think that it could be worthwhile to make the `plugin_path` configurable, as not every distribution might want to install plugins to `%_libdir` (I think `%_libexecdir` might be a better fit depending on the distro policy).
> 
> I just took the path which was already there, so this would require changes in other places. This pr, just makes the phoebe useable without the need of an extra edit of the configuration files.

Makes sense, then this PR looks good to me :+1:

**Review by dcermak — APPROVED** [review]

**Comment by mvarlese** [comment]
Thanks @mslacken

**Pull request merged**
