### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by dcermak**
This is a draft pull request to add unit tests leveraging the cmocka library for the `allocateMemoryBasedOnInputAndMaxLearningValues` function.

Currently, the CI fails because `allocateMemoryBasedOnInputAndMaxLearningValues` has a bug: if the file from which it tries to read the number of lines has a **really** long line, then it reports a wrong number of lines. Also, it counts one line less than there actually are in the file. Is that intentional?

### CODE REVIEW

**Comment by dcermak** [comment]
> Also, it counts one line less than there actually are in the file. Is that intentional?

@mvarlese @shunghsiyu :point_up_2: ?

**Comment by shunghsiyu** [comment]
I don't think those behaviors are intentional, but @mvarlese knows this part of the code better than I do, so you can take his answer over mine anytime :wink:

**Comment by mvarlese** [comment]
> > Also, it counts one line less than there actually are in the file. Is that intentional?
> 
> @mvarlese @shunghsiyu  ?

Yes, it is intentional as the first one needs to be discarded as it represents the "columns titles" on the first row of the CSV/Excel file.

**Comment by dcermak** [comment]
Ok, I think I've got this PR into a relatively satisfactory state (from my POV at least :wink:).

Most of the changes are just related to the addition of CMocka as the unit testing framework and a relatively simple test, that illustrates some of the more advanced mocking features and should provide some guidance for later tests. The only notable change outside of the test directory is that I moved `tests/settings.json` to `conf/settings.json` as I've added the option to completely omit the generation of the tests for now (thus cmocka is not required to build phoeβe, only as a test dependency).

**Comment by mvarlese** [comment]
I am super happy to see this patch in shape. :)

Once again, thanks for your effort here, truly appreciated!

**Pull request merged**
